# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(error_messages={'unique': 'Este titulo no es unico, intenta de nuevo.'}, help_text='debe ser un titulo unico.', max_length=250, unique=True, verbose_name='Movie Name')),
            ],
        ),
    ]
