# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Studio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
