# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Gender',
            field=models.CharField(default='draft', max_length=120),
        ),
    ]
