# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Created',
            field=models.DateField(auto_now=True),
        ),
    ]
