# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
