# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import movie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20180218_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Studio',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[movie.validators.validacion_studio]),
        ),
    ]
