# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20180218_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
